### ISSUE TITLE
End-of-life Node Version dependency

### ISSUE THREAD

**Issue by riccardo-giuffre** [dmitryserbin/azdev-release-orchestrator#108]
Hi @dmitryserbin ! First of all, great pictures :) and thanks for your work, the release orchestrator has been an amazing tool to integrate in both classics releases and yaml pipelines.

Here to open a small issue (given you have the time to handle it) regarding dependency of some component of both R.O. V2 & V3 on Node Version 10.0.

![node-issue](https://github.com/user-attachments/assets/aea26be3-3473-4996-bbd6-37f1c9b73ab4)

Thanks for your service 🫡

**Comment by dmitryserbin** [comment]
#109

**Comment by dmitryserbin** [comment]
Resolved, to be release in 3.2

**Comment by riccardo-giuffre** [comment]
Thank you! @dmitryserbin , appreciate the effort 💯
