### ISSUE TITLE
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

### ISSUE THREAD

**Issue by leec88** [dmitryserbin/azdev-release-orchestrator#115]
We have been running version 2 of the Release Orchestrator for very long time on linux agents but since today we have been receiving the below.

![image](https://github.com/user-attachments/assets/facb7ae6-b00e-4ff9-ac6e-80206a00aaaa)

I see there was an update for version 3 has there been any changes to version 2 to stop it running on linux devops agents?

**Comment by dmitryserbin** [comment]
Hi, both tasks have been updated to Node 20 as the older version is about to be deprecated.

I suspect this is the case. Are you using self hosted agents? You may need to update NodeJs.

**Comment by ghost** [comment]
Hi, we are using this task on a Windows build agent and we have been getting these errors since your last commit as well

##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

**Comment by dmitryserbin** [comment]
Thanks for letting me know. I'll see if I can add legacy Node executors to maintain the support for older Azure DevOps Server versions.

**Comment by dmitryserbin** [comment]
#116

**Comment by dmitryserbin** [comment]
Released 3.2.751, please retest and let me know if you have any issues.

**Comment by leec88** [comment]
Thank for looking into this. The task now working for us

**Comment by ghost** [comment]
Yes, thank you for the update. The task is also working for us as well
