### ISSUE TITLE
Enhancement request: Stop release upon Approval failure

### ISSUE THREAD

**Issue by TimothyTam** [dmitryserbin/azdev-release-orchestrator#23]
Hello, Is it possible to end the release once it hits "Stage <Stage 1> (129) cannot be approved by <Release-98> (Project Collection Build Service)"

It seems to be retrying forever.

I just want to trigger the release and let others manually approve.

Thank you

**Comment by dmitryserbin** [comment]
Thanks for using the extension. There is one hour timeout for approval retry. I could make it configurable in the task (so you set it to 0) and quit the job with partially succeeded status or something.

**Comment by TimothyTam** [comment]
Please do, it would be great! Thanks!

**Comment by dmitryserbin** [comment]
This will be addressed in the next release.
