### ISSUE TITLE
Calling a release that uses the same Agent

### ISSUE THREAD

**Issue by mhmacleod** [dmitryserbin/azdev-release-orchestrator#25]
I have a release that uses the orchestrator to call another release; both of which uses the same Agent.

Problem is that it seems to be blocking in a deadlock as the first release is waiting for the second to complete but in order for the second to start it needs to wait for the Agent to be freed up; or it seems to be this way as it gets stuck on that step for a long time.

Is this true? And is there any way to mitigate this besides allocating to different Agents (which we currently do not have)

**Comment by dmitryserbin** [comment]
My guess is you're using free Azure DevOps hosted agents tier, which only allows you to [run one agent job at a time](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops). You can try making your project public, this will give you 10 parallel jobs. You can also run self-hosted agents.

Hope this helps.

**Comment by mhmacleod** [comment]
Understood; not a bug. Thanks.
