### ISSUE TITLE
Trigger last stable release?

### ISSUE THREAD

**Issue by evertonmc** [dmitryserbin/azdev-release-orchestrator#26]
Is it possible to trigger a release with the artifacts of the last successful release?
![image](https://user-images.githubusercontent.com/5794688/66898580-c014e200-eff9-11e9-8390-54f56a888d26.png)

**Comment by dmitryserbin** [comment]
Thanks for your feedback. Currently, when selecting `latest release`, the orchestrator will find and re-deploy a latest available release regardless status of the target stage (i.e. it may re-run failed stages, if any).

It might be possible to add target stage status filter for latest release deployment, so it will only proceed with successfully deployed stages. I will add this to the backlog.

**Comment by evertonmc** [comment]
cool, thanks. 
Use case: recreate environment every morning with last successful release of every component.

**Comment by dmitryserbin** [comment]
Meanwhile, you can try tagging last successful release artifact using [this extension](https://marketplace.visualstudio.com/items?itemName=dmitryserbin.artifacts-tagger) and using artifact tag filter for the orchestrator job.

1) Successfully deploy stage
2) Add stage name tag to the deployed artifact (using task above
3) Run orchestrator with filter artifact tag = stage name

![image](https://user-images.githubusercontent.com/30379061/66959664-57943680-f0c7-11e9-9bbd-0a175485c425.png)

![image](https://user-images.githubusercontent.com/30379061/66959820-ac37b180-f0c7-11e9-8bf2-dd1247e7ff14.png)

**Comment by evertonmc** [comment]
Thanks, but this only works for build artifacts coming from the same project as the release pipeline, which don't apply for me

**Comment by dmitryserbin** [comment]
This will be addressed in the next release.
