### ISSUE TITLE
specify build for all pipelines

### ISSUE THREAD

**Issue by chakaSA** [dmitryserbin/azdev-release-orchestrator#28]
Hi

I want to select the build number and then this build must be used by the remote pipelines.
In my test I select the build which downloads the correct artifacts, but the remote build uses the latest build instead.

How can I pass the build to all the remote pipelines I trigger?

Thanks
Jacques

**Comment by dmitryserbin** [comment]
You can try tagging your build with unique tag and using tag artifact filter in the Orchestrator - this is how we force the task to use specific build we want. Try using [Artifacts Tagger](https://marketplace.visualstudio.com/items?itemName=dmitryserbin.artifacts-tagger) extension for tagging your build.
