### ISSUE TITLE
[error]No <RELEASE_DEFINITION> artifact matching filter (version: undefined, branch: master) criteria found

### ISSUE THREAD

**Issue by Klippertjen** [dmitryserbin/azdev-release-orchestrator#37]
![image](https://user-images.githubusercontent.com/53306279/77521651-51c72c00-6e83-11ea-8935-03e9ebd42483.png)

Hello,

When using these settings, the error 'No <THE_NAME_OF_THE_RELEASE_DEFINITION> artifact matching filter (version: undefined, branch: master) criteria found' is thrown. Could you make it possible to implicitly use the latest version of the selected branch? Or make it possible to choose between the latest version or a manually defined version?

The problem is that for the moment, the option of filtering the source branch does not work at all.

Best regards

**Comment by dmitryserbin** [comment]
Hi there, you need to specify full branch path i.e. `refs/heads/master`.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/30379061/77628415-e4171f00-6fac-11ea-8887-55859ca6275c.png">

Hope this helps!

**Comment by Klippertjen** [comment]
Hi, I understand, but we work with Git, so in our case we have to use 'master'. I was hoping by just defining 'master' it would take the latest version in that branch, but apparently you need to define the version as well?

**Comment by dmitryserbin** [comment]
It will take the latest version if your master branch if you specify `refs/heads/master`. You can specify path to any other branch in the same way `refs/heads/working/my_branch`.

Please give it a try - should work just fine.

**Comment by Klippertjen** [comment]
By using `refs/heads/master` it seems to be working correctly. I was mistakenly using `master` because it was mentioned to use it when working with Git artifacts and we are working with Git repositories.

Thank you very much for your help.

**Comment by dmitryserbin** [comment]
Glad it's all good now. I'll see if I can update documentation to make it more clear. Thanks!
