### ISSUE TITLE
Feature request: YAML multi-stage pipelines support

### ISSUE THREAD

**Issue by ricohomewood** [dmitryserbin/azdev-release-orchestrator#39]
Could we have the ability to trigger a CI/CD YAML pipeline?  Releases are now considered as classic by Microsoft with the introduction of deployment jobs in YAML pipelines so CI and CD are now all in the same pipelines section of Azure DevOps.

Please could we have the ability to trigger a Pipeline and not just the classic releases?

Reference:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops

**Comment by dmitryserbin** [comment]
This is exactly my thinking. In Azure DevOps YAML pipelines is the way forward, and at this stage the feature is mature enough to make it work with the Orchestrator.

The tricky part is that [Build API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/?view=azure-devops-rest-5.1) is a completely different beast and it will require full code refactoring and will lead to a lot of breaking changes in the task.

I plan to start working on the Orchestrator V2 with YAML pipelines support next month. Will need to run new version in preview mode for some time. Will keep you guys updated, stay in touch.

**Comment by bensgroi** [comment]
Hey @dmitryserbin, just curious if there are any updates on this feature, or an estimated timeline? Thanks

**Comment by dmitryserbin** [comment]
@bensgroi this is number one item in my todo list. But, unfortunately it is not very straight forward and requires a lot of work as YAML pipelines is another Azure DevOps API to deal with. I will most likely have to create a new major version of the task for proper YAML pipelines support.

There is no ETA at this stage, but I'm hoping to start working on it within the next month or two, while it's still quite at work.

**Comment by dmitryserbin** [comment]
Just a quick update - I'm about to start working on V3 of the task which will be working with YAML pipelines.

Please stay tuned.

**Comment by CurlyBytes** [comment]
Looking forward on this one sir @dmitryserbin  ^^

**Comment by dmitryserbin** [comment]
Just a quick update - V3 with YAML pipelines support will soon be available in public preview.

**Comment by CurlyBytes** [comment]
Wow, the v3 branch looks promising, thanks a lot!

**Comment by dmitryserbin** [comment]
V3 is released to public preview.
