### ISSUE TITLE
Unable to use variable for release definition

### ISSUE THREAD

**Issue by keithpatton** [dmitryserbin/azdev-release-orchestrator#4]
We are finding that we cannot use a variable for the Release Definition field and must slect from the drop down. As we have many releases we wanted to use your task within a re-usable task group rather than having to clone it many times and hard code the release definition selection. 
We get the following error:

##[error]Unable to create new release. TypeError: Cannot read property 'map' of undefined

It would be good to understand if this is supposed to be supported or if it's a know issue?

**Comment by dmitryserbin** [comment]
Thanks for your feedback, this sounds like a valid concern.

At the moment, the Release Definition field in the task uses definition ID in the backend (name is just an alias in GUI), so you can try specifying definition ID as a variable.

However, I will look into that to see if it can be improved in future as using definition ID for reference in variables is not exactly user-friendly. I will also improve error handling to display a better error message when target definition is not found.

Please keep an eye on this issue and I will update you with the progress.

**Comment by keithpatton** [comment]
thanks for the quick response, will try the definition ID instead, it may be i can just add a task in the task group before calling the release orchestrator to get the ID so the user can still put in the name until this is fixed. great work on this task by the way it was EXACTLY what we were looking for to bypass our CD and control deployment to specific steps automatically.

**Comment by asifibrahim** [comment]
This task is helpful.  Is there a way to add option to not wait for triggered release to complete?

**Comment by dmitryserbin** [comment]
> This task is helpful. Is there a way to add option to not wait for triggered release to complete?

Yep, I could do that. Will have a look next week. Thanks

**Comment by asifibrahim** [comment]
Thanks a lot.  I will be waiting for it :)

**Comment by dmitryserbin** [comment]
> Thanks a lot. I will be waiting for it :)

Just a quick question, do you want to to skip progress tracking for new releases only or latest/specific as well? Thanks

**Comment by asifibrahim** [comment]
I was just trying to start another release and not track from the release which I started with.  Thanks

**Comment by dmitryserbin** [comment]
This is move into [backlog](https://github.com/dmitryserbin/azdev-release-orchestrator/wiki/Backlog) and will be addressed when possible.

**Comment by asifibrahim** [comment]
Can you also add passing a variable such build label to the newly started release or build.  Thnx

**Comment by dmitryserbin** [comment]
@asifibrahim do you mean [custom release variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)?

**Comment by asifibrahim** [comment]
yes,  I have Release which deploys code for Build01 to a Test env and after deployment triggers another Build02 to run sanity tests.  Need Build01 as a parameter to use in Build02 to document for which build sanity tests are executed, if possible.  Thanks

**Comment by dmitryserbin** [comment]
sure @asifibrahim this can be done - i've added to the backlog. thanks

**Comment by dmitryserbin** [comment]
This will be addressed in the next release.
