### ISSUE TITLE
Using Latest Release with Filtered Source Branch triggers old deploys

### ISSUE THREAD

**Issue by keithpatton** [dmitryserbin/azdev-release-orchestrator#41]
I attempted to use a configure the task to use Filter Source Branch with Latest Release as follows:

![Capture](https://user-images.githubusercontent.com/3859201/83936100-26ae7080-a814-11ea-94ed-570f760dfabb.JPG)

Unfortunately it started triggering deployments for the oldest, not the newest release when i used develop branch on my component. 

I found it used the latest release if i removed the Filter Source Branch, but i would really like to use this to deploy a specific release based on the branch of artifacts. 

Can you provide a reason as to why the very latest release would not be used when specifying Filter Source Branch?

**Comment by dmitryserbin** [comment]
Thanks for reporting this. I believe this scenario will be addressed in V2.
