### ISSUE TITLE
Release Orchestration

### ISSUE THREAD

**Issue by AshishNigamNoida** [dmitryserbin/azdev-release-orchestrator#57]
I have two different Release pipeline. In one pipeline using Release Orchestration agent to call second release pipeline . When we execute first Release pipeline the second release pipeline is showing "Waiting for running jobs to finish".

Please let me know how to fix this issue.

**Comment by dmitryserbin** [comment]
Hi @AshishNigamNoida, sorry for late reply. It doesn't sound like Release Orchestrator issue, but you may need to re-produce it with debug mode on and share the logs.

> To enable debug mode to help troubleshooting issues, please configure DEBUG=release-orchestrator:* custom release variable.
