### ISSUE TITLE
How to execute multiple Release pipelines using this Release Orchestrator? 

### ISSUE THREAD

**Issue by AshishNigamNoida** [dmitryserbin/azdev-release-orchestrator#58]
How to execute multiple Release pipelines using this Release Orchestrator?  What is the option to set multiple Release pipelines in one go?

**Comment by dmitryserbin** [comment]
Hi, unfortunately multiple releases/pipelines are not supposed. You need to use multiple instances of the task to orchestrate more than one pipeline at a time.
