### ISSUE TITLE
V2 Orchestrator no longer supports comma separated release definition ids

### ISSUE THREAD

**Issue by harisubramaniam1** [dmitryserbin/azdev-release-orchestrator#64]
While using V1 orchestrator, it was possible to supply multiple release definition ids as a comma separated value.
For ex - 62,63,64 etc

Whereas in V2 orch, looks like csv of release def ids are no longer supported?

**Comment by dmitryserbin** [comment]
I don't think it ever supported this. V2 & V3 definitely won't, sorry.
