### ISSUE TITLE
No aritfact version id is specified corresponding to artifact source

### ISSUE THREAD

**Issue by kboro** [dmitryserbin/azdev-release-orchestrator#7]
Hello,

Thanks for your extension which looks really promising. However when I try to Create Release with following settings:

![image](https://user-images.githubusercontent.com/28050787/54530129-3711cb80-4982-11e9-9687-af15943449c9.png)

I have following error:

VS402962: No artifact version id is specified corresponding to artifact source 'Source-Alias'. Specify a valid value and try again.

Moreover when I choose "Artifacts Strategy" with "Specific Artifacts" I can see list of Artiffacts linked to Release Definition.  Issue only occurs when I choose "Create Release" with "Default Artifacts"

Version on Premise: TFS 2018 Update.3

**Comment by dmitryserbin** [comment]
Thanks for using the extension.

Unfortunately, I don't have TFS 2018 around to test against it, however, I'm hoping this issue will be resolved with [the next release](https://github.com/dmitryserbin/azdev-release-orchestrator/pull/6) as it introduces some changes to 'new release' artifacts filter.

ETA - next day or two. Please, keep me updated on the results.

**Comment by kboro** [comment]
will do, ty sir!

**Comment by dmitryserbin** [comment]
To be addressed in #6 (hopefully)

**Comment by dmitryserbin** [comment]
Version 1.2.0 has been pushed. Please check if it resolves the issues.

**Comment by kboro** [comment]
It has been fixed with 1.2.0. Thank You !
