### ISSUE TITLE
Can we integrate yaml pipeline and classic pipeline through Release Orchestrator task?

### ISSUE THREAD

**Issue by aakanshaverma1310** [dmitryserbin/azdev-release-orchestrator#77]
Can we integrate yaml pipeline and classic pipeline through Release Orchestrator pipeline?

For example -
I have to run a sequence of pipelines where i have to run few classic editor pipelines and then few yaml pipleines and then again few classic pipelines. So can this be automate through release orchestrator task?

**Comment by dmitryserbin** [comment]
Yes it is possible. You need to use V2 version of the task to target classic pipelines and V3 for YAML. Both tasks can work side by side in a pipeline no problem. 

Hope this helps.

**Comment by aakanshaverma1310** [comment]
Tried out that. 
but fall into this error. 
what is understand is we have a group with the name **Project Collection Build Service** which needs Queue build permissions,  so we have given Allowed permission in Manage Security to **Project Collection Build Service**
But still getting this error. 

Could you suggest something.

Error: TF215106: Access denied. Project Collection Build Service (my-org-name) needs Queue builds permissions for build pipeline 937:ADF-pipeline in team project my-ado-project-name to perform the action. For more information, contact the Azure DevOps administrator.
    at RestClient.<anonymous> (/home/vsts/work/_tasks/releaseorchestrator_5d38d46b-4c0a-4c14-8f0c-04df59e4dc27/3.0.1663/node_modules/typed-rest-client/RestClient.js:202:31)

**Comment by dmitryserbin** [comment]
sounds like permissions issue. you need to double check you've done it right. you need to set permissions for `project build service`, NOT `project collection build service`.

here's a few scree short help you with that.

for YAML:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/30379061/172957195-4e9a4a44-f4c9-494c-9153-82e951223bd7.png">

![image](https://user-images.githubusercontent.com/30379061/172958353-e1e90acf-4b10-4ee8-afba-0d5d6924546c.png)

for classic:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/30379061/172957378-280681ab-7d59-4514-8c64-6111e7354237.png">

![image](https://user-images.githubusercontent.com/30379061/172957685-76401e4b-bafc-4c6b-ac8f-8b6b8e8e67c8.png)

**Comment by aakanshaverma1310** [comment]
Thanks

**Comment by aakanshaverma1310** [comment]
error im getting - 
![image](https://user-images.githubusercontent.com/45385925/174069190-6d6dbe1d-15df-4fb5-ac67-ba79e1632906.png)
This is my release pipeline.. which is working fine if i run it manually.. all these variables are 'settable at release time'
![image](https://user-images.githubusercontent.com/45385925/174069307-5b982fc4-4dca-4c1f-ae1a-91e1e65ed85c.png)

can you please point out the error.. what is missing out. Thanks in advance.

**Comment by aakanshaverma1310** [comment]
My yaml pipeline has the stages and requires approval at the upper environment, PFB image

![image](https://user-images.githubusercontent.com/45385925/174102343-6485cefe-7e37-475d-a26c-b69ab5f85d49.png)

If I run this pipeline through release orchestrator pipeline, then the pipeline keeps on running after dev stage gets completes, and show below results 

![image](https://user-images.githubusercontent.com/45385925/174103854-49b6f604-dce3-43ed-b619-ce6707df79a8.png)


my task -

                    - task: releaseorchestrator@3
                      inputs:
                        endpointType: 'integrated'
                        projectName: 'my-project'
                        definitionName: 'Create Templates Indexer'
                        strategy: 'new'
                        stages: 'Release to Dev,Release to QA,Release to INT,Release to Prod'
                        branchName: 'main'
                        updateInterval: 5
                        stageStartAttempts: 10
                        stageStartInterval: 60
                        approvalInterval: 60
                        approvalAttempts: 10

I tried providing stage:'Release to Dev' only, but then i get below error -

![image](https://user-images.githubusercontent.com/45385925/174104600-c1092cb2-5913-4a1f-863b-f9a70f1d90a9.png)

Do you think you can suggest something here?

**Comment by aakanshaverma1310** [comment]
@dmitryserbin pls check my comment

**Comment by dmitryserbin** [comment]
> If I run this pipeline through release orchestrator pipeline, then the pipeline keeps on running after dev stage gets completes, and show below results

@aakanshaverma1310 seems like you build service account doesn't have approval rights to the environment. You need to add it to the approval users first i.e. next the the real people who normally approve your releases.

**Comment by aakanshaverma1310** [comment]
I have few release variables like below.. 

![image](https://user-images.githubusercontent.com/45385925/174297943-fc68ac2e-a3b3-4b2b-9fb6-203a6a4349ad.png)

im passing their values from release orchestrator task, like below

                    - task: releaseorchestrator@2
                      displayName: 'disable-cdc-job'
                      enabled: true
                      inputs:
                        endpointType: 'integrated'
                        projectName: 'myproject'
                        definitionName: 'CDC-Enable-Disable-Release'
                        releaseStrategy: 'create'
                        definitionStage: 'Dev'
                        releaseVariables: Dev-EnableCDCCandidate=true
                        approvalRetry: 0
                        updateInterval: 5 


but i get below error - 

![image](https://user-images.githubusercontent.com/45385925/174298304-81eefd9b-af36-4e88-9187-29aed5c257dc.png)


My intention is to pass the value to my release variables from release orchestrator task. How can  achieve that?
note - i can not set release variable's scope to release .
