### ISSUE TITLE
Specific run - buildNumber vs buildName

### ISSUE THREAD

**Issue by DanieleS82** [dmitryserbin/azdev-release-orchestrator#91]
Hi,
looking into docs ([here](https://github.com/dmitryserbin/azdev-release-orchestrator/blob/master/Docs/OrchestratorV3.md#specific-run)) to execute a specific pipeline version, in the YAML example you show to use:
`buildNumber: <value>`

You write also:
<html><body>

Parameter | Description
-- | --
buildNumber | Target build number (i.e. build name)

</body>
</html>

But the field _buildNumber_ is not recognized as valid and after some research, the right field must be:
`buildName: <value>`

It's only a documentation error?

**Comment by dmitryserbin** [comment]
Thanks for reporting, looks like a bug, I will look into it.

**Comment by dmitryserbin** [comment]
Fixed

**Comment by dmitryserbin** [comment]
Released 3.1.1890
